{application,nanoid,
             [{config_mtime,1751956423},
              {compile_env,[{nanoid,[alphabet],error},{nanoid,[size],error}]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,crypto]},
              {description,"Elixir port of NanoID (https://github.com/ai/nanoid), a tiny, secure URL-friendly unique string ID generator."},
              {modules,['Elixir.Nanoid','Elixir.Nanoid.Configuration',
                        'Elixir.Nanoid.NonSecure','Elixir.Nanoid.Secure']},
              {registered,[]},
              {vsn,"2.1.0"}]}.
